LOCAL_CONFIG = {
    "GEOJSON_DIR": "/absolute/path/to/3d_geojsons",
    "GEOTIFF_DIR": "/absolute/path/to/geotiffs",
    "OUTPUT_DIR": "/absolute/path/to/outputs",
    "API_KEY": "YOUR_GOOGLE_STREET_VIEW_API_KEY",
    "STREETVIEW_SEARCH_SOURCE": "outdoor",
    "STREETVIEW_GOOGLE_IMAGERY_ONLY": True,
    # Keep persistent API response/image caching disabled unless your Google
    # Maps Platform terms and application policy explicitly permit it.
    "ENABLE_STREETVIEW_CACHE": False,
    "ENABLE_DGM_CAMERA_ELEVATION": True,
    "DGM_BASE_MAX_INLIER_ABS_DIFFERENCE_M": 0.75,
    "DGM_BASE_MAX_MEDIAN_ABS_DIFFERENCE_M": 0.50,
    # Applied only after every facade/roof texture has been finalized.
    "ENABLE_POSTTEXTURE_BASE_LEVEL_REPAIR": True,
    "POSTTEXTURE_BASE_LEVEL_TOLERANCE_M": 0.001,
    "POSTTEXTURE_EXTENSION_DOMINANT_COLOR_BITS": 5,
    "POSTTEXTURE_EXTENSION_MAX_COLOR_SAMPLES": 500000,
    "ENABLE_FACADE_SOURCE_MODEL_VISIBILITY": True,
    "ENABLE_OSM_EXTERNAL_BUILDING_OCCLUSION": True,
    "OSM_BUILDING_QUERY_RADIUS_M": 120.0,
    "OSM_BUILDING_CLEAR_OCCLUSION_FRACTION": 0.005,
    "OSM_BUILDING_PREFIT_HARD_REJECT_FRACTION": 0.97,
    "OSM_BUILDING_USE_DGM_TERRAIN": True,
    "OSM_BUILDING_TERRAIN_MAX_SAMPLES": 9,
    "OSM_BUILDING_TERRAIN_TOP_MARGIN_M": 0.5,
    "OSM_BUILDING_REQUIRE_CORRIDOR_INTERSECTION": False,
    "ENABLE_ORTHO_FIT": False,
    "ENABLE_HOUGH_SINGLE_SIDE_WARP": True,
    "ENABLE_POST_HOUGH_ROOF_STRUCTURE_REMOVAL": True,
    "POST_HOUGH_ROOF_CONNECTION_TOLERANCE_PX": 3,
    "POST_HOUGH_ROOF_BOUNDARY_SEED_PX": 2,
    "POST_HOUGH_ROOF_MIN_DIVIDER_COMPONENT_AREA_PX": 32,
    "POST_HOUGH_ROOF_MIN_PARTITION_AREA_PX": 80,
    "POST_HOUGH_ROOF_MIN_PARTITION_FRACTION": 0.03,
    "LAMA_MODEL_PATH": "../lama_model/inpainting_lama_2025jan.onnx",
    "LAMA_BACKEND": "auto",
    "BIG_LAMA_GENERATOR_PATH": "../lama_model/big-lama/models/generator.pt",
    "BIG_LAMA_DEVICE": "auto",
    "BIG_LAMA_CONTEXT_PX": 128,
    "BIG_LAMA_MAX_SIDE_PX": 1280,
    "BIG_LAMA_MAX_PIXELS": 1000000,
    "BIG_LAMA_ENABLE_REFINEMENT": False,
    "BIG_LAMA_REFINEMENT_ITERATIONS": 15,
    "BIG_LAMA_REFINEMENT_LEARNING_RATE": 0.002,
    "BIG_LAMA_REFINEMENT_MIN_SIDE": 512,
    "BIG_LAMA_REFINEMENT_MAX_SCALES": 2,
    "BIG_LAMA_REFINEMENT_MAX_PIXELS": 400000,
    # Quality/speed controls for the fixed-512 ONNX model. Native-resolution
    # overlapping tiles remove the blur caused by one global 512x512 resize.
    "LAMA_ENABLE_HIGH_RES_TILING": True,
    "LAMA_TILE_OVERLAP_PX": 96,
    "LAMA_MAX_TILES": 64,
    "LAMA_TILE_DETAIL_SIGMA_PX": 16.0,
    "LAMA_TILE_LOW_FREQUENCY_WEIGHT": 0.0,
    "LAMA_TILE_DETAIL_STRENGTH": 0.75,
    "LAMA_TILE_DETAIL_MAX_DELTA": 40.0,
    "LAMA_MASK_DILATE_PX": 8,
    "LAMA_COMPOSITE_FEATHER_PX": 4,
    "TEXTURE_TRANSPARENT_EDGE_BLEED_PX": 16,
    "SAM3_PROMPT_FACADE": "building facade",
    "SAM3_PROMPT_FACADE_REFINEMENT": "building walls",
    "SAM3_PROMPT_ROOF": "roof",
    "ENABLE_MODEL_DEPTH_PREFIT_SEMANTIC_GUIDANCE": True,
    "ENABLE_MODEL_DEPTH_PREFIT_STRICT_ROOF_GUIDANCE": True,
    "MODEL_DEPTH_PREFIT_IMAGE_BORDER_EXCLUSION_PX": 2,
    "MODEL_DEPTH_BOUNDARY_IMAGE_BORDER_EPSILON_PX": 0.5,
    # Optional fixed, automatic prompt library used before depth-global fits.
    # Add local occluder concepts here without changing pipeline code.
    "MODEL_DEPTH_PREFIT_SEMANTIC_PROMPT_LIBRARY": {
        "building": ("building",),
        "roof": ("building roof",),
        "sky": ("sky",),
        "vegetation": ("tree", "bush", "hedge"),
        "ground": ("road", "ground"),
        "occluder": (
            "vehicle",
            "person",
            "traffic sign",
            "signboard",
            "advertising board",
            "billboard",
            "street furniture",
            "pole",
            "scaffolding",
            "retaining wall",
            "garden boundary wall",
            "fence",
            "gate",
        ),
        "generic_occluder": (
            "foreground object",
            "object in front of building",
        ),
    },
    # This bare-roof role is reused only by later post-Hough cleanup; it does
    # not participate in target selection or fitting guidance.
    "MODEL_DEPTH_PREFIT_DOWNSTREAM_ROOF_PROMPTS": ("roof",),
    "MODEL_DEPTH_BOUNDARY_ANCHOR_MAX_TRANSLATION_PX": 50.0,
    "MODEL_DEPTH_BOUNDARY_ANCHOR_MAX_TRANSLATION_FRACTION": 0.25,
    "MODEL_DEPTH_PREFIT_VISIBILITY_MIN_TARGET_SUPPORT_FRACTION": 0.10,
    "MODEL_DEPTH_PREFIT_VISIBILITY_MAX_OCCLUDER_FRACTION": 0.80,
    "MODEL_DEPTH_PREFIT_VISIBILITY_MAX_TARGET_AREA_RATIO": 6.0,
    "MODEL_DEPTH_PREFIT_OCCLUDER_DILATION_PX": 3,
    "FACADE_ALIGNMENT_MODE": "depth_global",  # or "wall_only"
}
