name: lod2_texture_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.26,<2
  - pandas
  - geopandas
  - shapely
  - pyproj
  - rasterio<1.5
  - requests
  - pillow
  - opencv
  - trimesh
  - scipy
  - matplotlib
  - fiona
  - pyogrio
  - setuptools<81
  - pip
  - pip:
      - einops
      - pycocotools
      - psutil
      - "triton-windows<3.7; platform_system=='Windows'"